# Generated by Django 4.2.4 on 2023-09-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
