# Generated by Django 4.2.6 on 2023-11-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletters',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
