# Generated by Django 4.2.4 on 2023-08-31 02:30

import ckeditor_uploader.fields
from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_group_options_post_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('pk',), 'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=15, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(validators=[posts.validators.validate_not_empty], verbose_name='Текст'),
        ),
    ]
