# Generated by Django 4.2.4 on 2023-09-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_options_alter_group_options_and_more'),
        ('users', '0004_profile_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(to='posts.post'),
        ),
    ]
